### ISSUE TITLE
Unverified InsecureRequestWarning Python3 SDK call for 

### ISSUE THREAD

**Issue by kaido89** [deep-security/automation-center-sdk-samples#12]
Got this warning for python3 when running the sample code 
https://github.com/deep-security/automation-center-sdk-samples/blob/master/python/src/computer_status_examples.py

`/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py:847:` InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: `https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings`

As Security tool, shouldn't it be fixing ssl request warnings?
Disabling the warning is not a great solution in my opinion
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

**Comment by scott-bro** [comment]
@kaido89 Thank you for raising this issue. I agree that disabling the warning should not be done by default. I have commented out that line of code in Main.py.

Thanks for using the samples!
