### ISSUE TITLE
expand method does not exist

### ISSUE THREAD

**Issue by upgreyd** [deep-security/automation-center-sdk-samples#13]
>>> computers_api = api.ComputersApi(api.ApiClient(configuration))
>>> computers = computers_api.list_computers(api_version, expand=expand.list(), overrides=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'expand' is not defined

**Comment by upgreyd** [comment]
>>> expand = api.Expand()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'deepsecurity' has no attribute 'Expand'
>>> expand.add(expand.intrusion_prevention)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'expand' is not defined

**Comment by scott-bro** [comment]
What version of the SDK are you using?

**Comment by scott-bro** [comment]
The expand parameter was introduced in Deep Security as a Service on May 22, 2019 ( https://automation.deepsecurity.trendmicro.com/article/12_5/changelog?platform=dsaas#may-22-2019) and in Deep Security 12.0 (https://automation.deepsecurity.trendmicro.com/article/12_0/changelog?platform=on-premise#enhancements)
