### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TenantsApi'

### ISSUE THREAD

**Issue by Ed-Davis** [deep-security/automation-center-sdk-samples#5]
automation-center-sdk-samples/python/src/tenant_examples.py", line 82, in get_ip_states_for_tenant
    state = api.TenantsApi(api.ApiClient(configuration)).describe_tenant(tenant_id, api_version).tenant_state
AttributeError: 'module' object has no attribute 'TenantsApi'

The API module does not appear to have a function called TenantsApi, but it is called in the examples and is in the SDK documentation.

**Comment by scott-bro** [comment]
@Ed-Davis Which platform is your SDK for? If you are using the SDK for DSaaS, then no it won't have TenantsApi. You need the on-premise, AWS, or Azure SDK for the tenant API.

**Comment by scott-bro** [comment]
Closing. Please re-open if the issue is not resolved.
